bot:
  allow_dm: true
  allow_gc: true
  anti_age_ban: true
  batch_messages: true
  batch_wait_time: 10.0
  disable_mentions: true
  groq_model: llama3-70b-8192
  help_command_enabled: false
  hold_conversation: true
  openai_model: gpt-4o
  owner_id: 1091212878855540807
  prefix: '!'
  realistic_typing: true
  reply_ping: true
notifications:
  error_webhook: ''
  ratelimit_notifications: false
